--- 
- 
  name: "unarchive backend files"
  unarchive: 
    dest: /home/ubuntu/
    src: backend.tar.gz
- 
  become: true
  name: "install pm2"
  npm: 
    global: true
    name: pm2
    production: true
    state: present
- 
  name: "Start PM2"
  shell: |-
      cd /home/ubuntu/backend
      pm2 start npm --name backend -- start
